print("Intro Python")
print("starting to test in Python")
print("1. Use function print to show different text in the screen")
print("2. use function print to show mathematic operations and their results")
print( " a. example:")
print("  i. 1+1= 2")
print("  ii. 90+430=520")
print("Show results for 5+4") 
print(5+4)
print("Show results for 6*3") 
print(6*3)
print("Show results for 36-9") 
print(36-9)
print("Show results for 72/2")
print(72/2)
